### ISSUE TITLE
Does not delete full history

### ISSUE THREAD

**Issue by pconwell** [timendum/reddit-privacy#2]
To duplicate:

1. Run reddit-privacy and delete history X number of days. (let's say 90 for sake of example)
2. Sign in to account
3. Go to `https://www.reddit.com/user/YOURUSERNAME/?sort=top` or `https://www.reddit.com/user/YOURUSERNAME/comments/?sort=controversial`
4. You will see your top comments from MORE THAN 90 days ago

If you go under `https://www.reddit.com/user/YOURUSERNAME/comments/`, it will correctly show that everything over 90 days has been deleted (or at least is not showing anymore).

I did some snooping around but haven't come up with anything useful yet. I'll keep looking.

**Comment by timendum** [comment]
You are definitively right, I think it is caused by Reddit API limit of 1000 items.  
Also even if I have less then 1000 comments, some are fetched, maybe because deleted comments still counts?

Anyway I've done what I can in 0da97d7a3f8b6bfed533b71ccac2a2148466c817, the script now fetch also from top, hot (maybe too much) and controversial listing, to create a set of all the content and the search in them.

**Comment by pconwell** [comment]
Nice!

Yeah, from what I'm seeing `top` and `controversial` should cover everything but it can't hurt anything to run `hot` as well.
